jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.11.9'
    displayName: 'Use Node.js 10.15.1'
  - script: npm ci
  - script: npm run test
- job: Windows
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.11.9'
    displayName: 'Use Node.js 10.15.1'
  - script: npm ci
  - script: npm run test