jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: npm ci
  - script: npm run test
- job: Windows
  pool:
    vmImage: 'windows-2019'
  steps:
  - script: npm ci
  - script: npm run test