jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: NodeTool@0
    inputs:
      checkLatest: true
    displayName: 'Use Node.js latest'
  - script: npm ci
  - script: npm run test
- job: Windows
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: NodeTool@0
    inputs:
      checkLatest: true
    displayName: 'Use Node.js latest'
  - script: npm ci
  - script: npm run test