trigger:
- master

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.15.1'
    displayName: 'Use Node.js 10.15.1'
  - script: |
      npm ci
    displayName: 'Install dependencies'
  - script: |
      npm run test
    displayName: 'Run Tests'
- job: Windows
  pool:
    vmImage: 'windows-2019'
  steps:
  - task: NodeTool@0
    inputs:
    versionSpec: '10.15.1'
    displayName: 'Use Node.js 10.15.1'
  - script: |
        npm ci
    displayName: 'Install dependencies'
  - script: |
        npm run test
    displayName: 'Run Tests'